import type { Metadata } from "next";
import { Bodoni_Moda, Uncial_Antiqua } from "next/font/google";
import "./globals.css";

const bodoniModa = Bodoni_Moda({
  subsets: ["latin"],
  variable: "--font-bodoni-moda",
});

const uncialAntiqua = Uncial_Antiqua({
  subsets: ["latin"],
  weight: "400",
  variable: "--font-uncial-antiqua",
});

export const metadata: Metadata = {
  title: "Azalea",
  description: "Generated by create next app",
  icons: {
    icon: "data:image/svg+xml,<svg xmlns=%22http://www.w3.org/2000/svg%22 viewBox=%220 0 100 100%22><text y=%22.9em%22 font-size=%2290%22>⚫</text></svg>"
  },
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${bodoniModa.variable} ${uncialAntiqua.variable} antialiased`}
      >
        {children}
      </body>
    </html>
  );
}
